### ISSUE TITLE
Question - Rotational conversion for target lights and lights from 3ds max to shapespark

### ISSUE THREAD

**Issue by stephen147** [shapespark/shapespark-extras-json#1]
I'm trying to see how to translate the rotational values of 3ds max to the yaw and the pitch values for shapespark.

How is this calculated when the roll is excluded from the corresponding x y z rotational values in 3ds max?

I can find no info for translating only to the yaw and pitch without the roll value.

Any help for this would be greatly appreciated.  Thanks.

**Comment by wmatyjewicz** [comment]
Assuming Z-up coordinate system, as in 3ds Max, you can compute `yaw` and `pitch` from a light `direction` unit vector using the following equations:

      yaw = atan2(-direction.x, direction.y)
      pitch = asin(direction.z)

**Comment by stephen147** [comment]
Thanks very much.

There was a slight error in the `direction.z` needed to be `-direction.z` and `-direction.x` was positive as this is translating as it should in Shapespark.

This is the working code written as a function:
```
/*
convertDirectionToYawPitchAsPoint2Value function

Translates any items point3 direction and returns it as
yaw and pitch in degrees as a point2 value.

Usage: convertDirectionToYawPitchAsPoint2Value <selection>
Returns: [<expr>, <expr>]
*/

fn convertDirectionToYawPitchAsPoint2Value theItem =
(
  direction = theItem.dir
  yaw = atan2(direction.x) (direction.y)
  pitch = asin(-direction.z)
  return [yaw, pitch]
  )

-- print ((convertDirectionToYawPitchAsPoint2Value $)[1] as string + " yaw")
-- print ((convertDirectionToYawPitchAsPoint2Value $)[2] as string + " pitch")
```
